/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 D.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/D.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials.Material}
        position={[0.212, 1.35, -0.046]}
        rotation={[1.58, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["Material.004"]}
        position={[-0.021, 1.276, 0.099]}
        rotation={[1.576, 0, 0]}
        scale={94.201}
      />
    </group>
  );
}

useGLTF.preload("/D.glb");
